### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by vitormicillo** [tu6ge/voyager-relation-selector#2]
Hi, can you provide this help in English ?
I believe this will help many people who use Voyager
thanks for the initiative

**Comment by tu6ge** [comment]
About relation selector, I have a new solution, this is [laravel form item](https://github.com/tu6ge/laravel-form-item), it has english documents, this is [link](https://tu6ge.github.io/laravel-form-item/en/), and [relation selector docs](https://tu6ge.github.io/laravel-form-item/en/form/cascader.html)

**Comment by tu6ge** [comment]
In voyager relation selector, I add chinese region info, therefore It is more suitable for chinese people. thank you
